### PR TITLE
fix the bad code

### PR DESCRIPTION
**Pull request by js6pak**

### CODE REVIEW

**Comment by HelpfulStranger999** [comment]
This glorious PR removes all the anti-patterns, offering a solid base upon which to rebuild the mod with actually good code that is maintainable, testable, stable, etc.

**Comment by cybershard** [comment]
LGTM

**Comment by DaemonBeast** [comment]
Bruh. I respect you Slushie 😎.

Also, here are a bunch of things that I advise you change:
- Use Reactor's Custom RPCs instead of your own one (I'm fairly sure this uses Reactor).
- Use a single RPC for setting roles (an RPC with a role ID and player ID) .

**Review by DorCoMaNdO — APPROVED** [review]
Never seen cleaner code in my entire life.

**Review by HelpfulStranger999 — APPROVED** [review]
SeemsGood

**Comment by ExoPlant** [comment]
Looks great! Thanks for your hard work @js6pak

**Comment by gabriel-nsiqueira** [comment]
I agree, this will make this much better @js6pak

**Comment by NotSugden** [comment]
tbh it would be better to rebuild this mod from scratch, no offense to slushie but the code is just horrific in most places

**Comment by roobscoob** [comment]
> tbh it would be better to rebuild this mod from scratch, no offense to slushie but the code is just horrific in most places

this is what pgg does

**Comment by ExoPlant** [comment]
lol

**Comment by js6pak** [comment]
u r lame poobscoob

**Comment by ExoPlant** [comment]
> 
> 
> u r lame poobscoob

Agree

**Pull request closed without merging**
